backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    files:
      - file: "src/content/projects.json"
        label: "Projects"
        name: "projects"
        format: "json"
        media_folder: "public/assets"   # uploads go under /public/assets
        public_folder: "/assets"
        fields:
          - label: "Projects"
            name: "projects"
            widget: "list"
            fields:
              - { label: "Title",  name: "title",  widget: "string" }
              - { label: "Year",   name: "year",   widget: "number" }
              - { label: "Type",   name: "type",   widget: "select", options: ["client","personal","game","art"] }
              - { label: "Order",  name: "order",  widget: "number", required: false }
              - { label: "Blurb",  name: "blurb",  widget: "text", required: false }
              - { label: "Image",  name: "image",  widget: "image" }
              - { label: "Video URL", name: "video", widget: "string", required: false }
              - { label: "Video file", name: "videoFile", widget: "file", required: false }
              - { label: "Tags",   name: "tags",   widget: "list", required: false }
